<../../../../mkconfig

LOCALE_ROOT=$ROOT/locale/zh_TW
COMPFLAG=-I$ROOT/appl/charon -I$LOCALE_ROOT/module
DIRS=\

LOCALE_MODULES=\

MODULES=${LOCALE_MODULES:%=$LOCALE_ROOT/module/%}

SYSMODULES= \

DISBIN=.\

TARGDATA=help.html\

TARG=\
	
DATADIR=$ROOT/services/webget


<./mkdis
