<../../../../mkconfig

LOCALE_ROOT=$ROOT/locale/zh_CN
COMPFLAG=-I$ROOT/appl/charon -I$LOCALE_ROOT/module
TARG=\
	charon_code.dis\
	charon_gui.dis\

MODULES=\

SYSMODULES=\

DISBIN=$ROOT/dis/charon

<../../mkdis
